let sunnySong = "https://www.last.fm/music/Maze/_/Joy+and+Pain"
let rainySong = "https://www.last.fm/music/Ann+Peebles/_/I+Can%27t+Stand+the+Rain"
let cloudySong = "https://www.last.fm/music/Kirk+Franklin/_/Brighter+Day"
let partlyCloudySong = "https://www.last.fm/music/The+Temptations/_/My+Girl"
let clearSong = "https://www.last.fm/music/Johnny+Nash/_/I+Can+See+Clearly+Now+-+Edit"
let mistSong = "https://www.last.fm/music/Sam+Cooke/_/A+Change+Is+Gonna+Come"